name: manage-your-labels
description: Label management across organization or user repositories

branding:
  icon: zap
  color: gray-dark

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -qqq --upgrade pip
      shell: bash
    - run: python3 -m pip install -qqq githubgql pyyaml
      shell: bash
    - run: $GITHUB_ACTION_PATH/src/mirror-own-labels
      shell: bash
